@AppointmentSystem.Api_HostAddress = http://localhost:5116


### Test API: Get Available Appointment Slots  
POST {{AppointmentSystem_Api_HostAddress}}/calendar/query  
Content-Type: application/json  
Accept: application/json  

{  
    "date": "2024-05-03",  
    "products": ["SolarPanels", "Heatpumps"],  
    "language": "German",  
    "rating": "Gold"  
}  

### Test API: Health Check (Optional)  
GET {{AppointmentSystem_Api_HostAddress}}/calender/  
Accept: application/json  